server:
  port: 8010
  servlet:
    context-path: /project
#配置mybatis-plus对应mapper.xml位置
#配置数据库mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/springboot-project?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: queena1991
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      active-connections: 6
      max-wait: 30000
      initial-size: 20
      min-idle: 5
      validation-query: select 1 from dual   #验证数据库心跳的SQL
      validation-query-timeout: 1
#设置上传文件大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis-plus:
  mapper-locations: classpath*:/mapper/com/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#minio配置
minio:
  endpoint: http://192.168.2.70:9000/
  accessKey: minioadmin
  secretKey: minioadmin

#缩我短连接服务key
shortUrl_key: 619b4c6aaee1e8601a82adb7@41bf4c7848ab5ef6e6bd1e4329c503c1
shortApi_url: http://api.suowo.cn/api.htm

#新浪短连接生成地址key
sina_short_url_key: d3587cfeb3797cd57c2476bf0bb2ef3d
sina_api_url: https://www.mynb8.com/api3/sina.html
#上传文件夹信息
upload-filePath: D:/xmjg/file
#openoffice安装地址
openoffice-path: D:/openoffice