server:
  port: 8009
  servlet:
    context-path: /project
#配置mybatis-plus对应mapper.xml位置
#配置数据库mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-project?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: queena1991
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      active-connections: 6
      max-wait: 30000
      initial-size: 20
      min-idle: 5
      validation-query: select 1 from dual   #验证数据库心跳的SQL
      validation-query-timeout: 1
mybatis-plus:
  mapper-locations: classpath*:/mapper/com/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

