server:
  port: 8070
  servlet:
    context-path: /project
#配置mybatis-plus对应mapper.xml位置
#配置数据库mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      mysql:
        username: xmjg_agcloud
        password: xmjg_agcloud
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.18.21.54:3309/xmjg_agcloud_620000?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
      clickhouse:
        url: jdbc:clickhouse://172.18.21.54:8124/xmjg_agcloud_620000?socket_timeout=30000000
        username: default
        password: 123456
        driverName: ru.yandex.clickhouse.ClickHouseDriver
      initial-size: 15
      min-idle: 15
      max-active: 200
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: ""
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      connection-properties: false
    dynamic:
      primary: mysql
      strict: false
  servlet:
    multipart:
      max-request-size: 1GB
      max-file-size: 1GB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  task:
    scheduling:
      pool:
        size: 10
  redis:
    host: localhost
    port: 6379
clickhouse:
  datasource:
    url: jdbc:clickhouse://172.18.25.88:8123/xmjg_agcloud_0329_68?socket_timeout=30000000
    username: default
    password: 123456
    driverName: ru.yandex.clickhouse.ClickHouseDriver
  #设置上传文件大小
mybatis-plus:
  mapper-locations: classpath*:/mapper/com/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_
#minio配置
minio:
  endpoint: http://192.168.2.68:9006
  accessKey: xmjg_agcloud
  secretKey: xmjg_agcloud

#缩我短连接服务key
shortUrl_key: 619b4c6aaee1e8601a82adb7@41bf4c7848ab5ef6e6bd1e4329c503c1
shortApi_url: http://api.suowo.cn/api.htm

#新浪短连接生成地址key
sina_short_url_key: d3587cfeb3797cd57c2476bf0bb2ef3d
sina_api_url: https://www.mynb8.com/api3/sina.html
#上传文件夹信息
upload-filePath: D:/xmjg/file

#上传二维码文件地址
qr_image_path: D:/xmjg/file/qr/

#tess4j语言地址
tess4j:
  tessdata:
    path: D:/xmjg/file/tess
#openoffice安装地址
openoffice-path: D:/openoffice
#swagger信息
agcloud:
  framework:
    swagger:
      enable: true
#设置统一返回时间格式
#redis订阅频道
redis:
  channel: jiashn,lovejiashn